version: '3'

services:
  frontend:
    image: frontend
    ports: 
      - 4200:4200

  database:
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hardlopen
    volumes:
      - ./database-postgres:/var/lib/postgresql/data  
      
  backend-runs: 
    image: backend-runs
    ports:
      - 8080:8080
    volumes:
      - ./database-postgres:/opt/hardlopen/database-postgres:rw
      - ./backend-runs/logfiles:/opt/hardlopen/backend-runs/logfiles:rw
      - ./backend-runs/src/main/resources/api-keys:/opt/hardlopen/backend-runs/target/src/main/resources/api-keys:ro
      - ./backend-runs/src/main/resources/runs:/opt/hardlopen/backend-runs/target/src/main/resources/runs:rw
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/hardlopen
      - location.url=http://backend-locations:8081/
    restart: always
    
  backend-locations: 
    image: backend-locations
    ports:
      - 8081:8081
    volumes:
      - ./backend-locations/src/main/resources/api-key:/opt/hardlopen/backend-locations/target/src/main/resources/api-key:ro
    restart: always 