version: '3'

services:
  frontend:
    image: frontend
    ports: 
      - 4200:4200

  database:
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hardlopen
    volumes:
      - ./database-postgres:/var/lib/postgresql/data  
      
  backend-runs: 
    image: backend-runs
    ports:
      - 8080:8080
    volumes:
      - ./database-postgres:/opt/hardlopen/database-postgres:rw
      - ./backend-runs/logfiles:/opt/hardlopen/backend-runs/logfiles:rw
      - ./backend-runs/src/main/resources/api-keys:/opt/hardlopen/backend-runs/target/src/main/resources/api-keys:ro
      - ./sample_runs:/opt/hardlopen/sample_runs:rw
    environment:
      - path-configuration.run-files-relative-path=/opt/hardlopen/sample_runs
      - spring.datasource.url=jdbc:postgresql://database:5432/hardlopen
      - service-address.location-service=http://backend-location:8081/
      - service-address.strava-service=http://backend-strava:8082/
      - service-address.tcx-reader-service=http://backend-tcxreader:8083/
    restart: always
    
  backend-location: 
    image: backend-location
    ports:
      - 8081:8081
    volumes:
      - ./backend-location/src/main/resources/api-key:/opt/hardlopen/backend-location/target/src/main/resources/api-key:ro
    restart: always 
    
  backend-strava: 
    image: backend-strava
    ports:
      - 8082:8082
    volumes:
      - ./backend-strava/src/main/resources/api-key:/opt/hardlopen/backend-strava/target/src/main/resources/api-key:ro
    restart: always 
    
  backend-tcxreader:
    image: backend-tcxreader
    volumes:
      - ./sample_runs:/opt/hardlopen/sample_runs:rw
    ports:
      - 8083:8083  
    restart: always 