version: '3'

services:
  frontend:
    image: frontend
    ports:
      - 4200:4200

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hardlopen
    volumes:
      - ./database-postgres:/var/lib/postgresql/data

  backend-runs:
    image: backend-runs
    ports:
      - 8080:8080
    volumes:
      - ./database-postgres:/opt/hardlopen/database-postgres:rw
      - ./docker-logfiles/backend-runs:/opt/hardlopen/backend-runs/target/logfiles:rw
      - ./backend-runs/src/main/resources/api-keys:/opt/hardlopen/backend-runs/target/src/main/resources/api-keys:ro
      - ./sample_runs:/opt/hardlopen/sample_runs:rw
    environment:
      - path-configuration.run-files-relative-path=/opt/hardlopen/sample_runs
      - spring.datasource.url=jdbc:postgresql://database:5432/hardlopen
      - service-address.location-service=http://backend-location:8081/
      - service-address.strava-service=http://backend-strava:8082/
      - service-address.tcx-reader-service=http://backend-tcxreader:8083/
      - service-address.trace-service=http://backend-trace-maker:8084/
    restart: on-failure:10

  backend-location:
    image: backend-location
    ports:
      - 8081:8081
    volumes:
      - ./backend-location/src/main/resources/api-key:/opt/hardlopen/backend-location/target/src/main/resources/api-key:ro
      - ./docker-logfiles/backend-location:/opt/hardlopen/backend-location/target/logfiles:rw
    restart: on-failure:10

  backend-strava:
    image: backend-strava
    ports:
      - 8082:8082
    volumes:
      - ./backend-strava/src/main/resources/api-key:/opt/hardlopen/backend-strava/target/src/main/resources/api-key:ro
      - ./docker-logfiles/backend-strava:/opt/hardlopen/backend-strava/target/logfiles:rw
    restart: on-failure:10

  backend-tcxreader:
    image: backend-tcxreader
    volumes:
      - ./sample_runs:/opt/hardlopen/sample_runs:rw
    ports:
      - 8083:8083
    restart: on-failure:10

  backend-trace-maker:
    image: backend-trace-maker
    ports:
      - 8084:8084
    volumes:
      - ./docker-logfiles/backend-trace-maker:/opt/hardlopen/backend-trace-maker/target/logfiles:rw
    restart: on-failure:10 
