version: '3'

services:
  frontend:
    image: frontend
    ports:
      - 4200:4200

  database:
    image: docker.io/postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hardlopen
    volumes:
      - /var/lib/postgresql/data

  backend-runs:
    image: backend-runs
    ports:
      - 8080:8080
    volumes:
      - ./database-postgres:/opt/hardlopen/database-postgres:rw
      - ./podman-logfiles/backend-runs:/opt/hardlopen/backend-runs/target/logfiles:rw
      - ./backend-runs/src/main/resources/api-keys:/opt/hardlopen/backend-runs/target/src/main/resources/api-keys:ro
      - /home/thomas/projecten/hardlopen/sample_runs:/opt/hardlopen/backend-runs/sample_runs:ro
    environment:
      - path-configuration.run-files-relative-path=/opt/hardlopen/sample_runs
      - spring.datasource.url=jdbc:postgresql://database:5432/hardlopen
      - service-address.location-service=http://backend-location:8081/
      - service-address.strava-service=http://backend-strava:8082/
      - service-address.tcx-reader-service=http://tcx-to-json:8083/
      - service-address.trace-service=http://backend-trace-maker:8084/
      - "SPRING_PROFILES_ACTIVE=postgres"
    restart: on-failure:10

  backend-location:
    image: backend-location
    ports:
      - 8081:8081
    volumes:
      - ./backend-location/src/main/resources/api-key:/opt/hardlopen/backend-location/target/src/main/resources/api-key:ro
      - ./podman-logfiles/backend-location:/opt/hardlopen/backend-location/target/logfiles:rw
    restart: on-failure:10

  backend-strava:
    image: backend-strava
    ports:
      - 8082:8082
    volumes:
      - ./backend-strava/src/main/resources/api-key:/opt/hardlopen/backend-strava/target/src/main/resources/api-key:ro
      - ./podman-logfiles/backend-strava:/opt/hardlopen/backend-strava/target/logfiles:rw
    restart: on-failure:10

  tcx-to-json:
    image: tcx-to-json
    volumes:
      - ./sample_runs:/opt/hardlopen/sample_runs:rw
    ports:
      - 8083:8080
    restart: on-failure:10

  backend-trace-maker:
    image: backend-trace-maker
    container_name: trace-maker
    ports:
      - 8084:8084
    volumes:
      - ./podman-logfiles/backend-trace-maker:/opt/hardlopen/backend-trace-maker/target/logfiles:rw
    restart: on-failure:10

  keycloak-db:
    image: docker.io/postgres:17
    container_name: keycloak-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret

  keycloak:
    image: docker.io/keycloak/keycloak:26.4
    container_name: keycloak
    command: start --import-realm
    ports:
      - "9000:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9000
      KC_HOSTNAME_STRICT: "false"
      KC_DIR: "/opt/keycloak/data/import/"
      KC_OVERRIDE: "true"
      KC_HEALTH_ENABLED: "true"
    volumes:
      - "./keycloak:/opt/keycloak/data/import"
    depends_on:
      - keycloak-db

  vaadin:
    image: vaadin
    container_name: vaadin
    ports:
      - 8085:8085
    environment:
      - spring.profiles.active=production
    depends_on:
      keycloak:
        condition: service_started
    restart: on-failure:10
    volumes:
      - ./podman-logfiles/vaadin:/app/logfiles:rw
