apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: 192.168.178.17:5000/frontend
    name: frontend
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4200
  selector:
    run: frontend
  type: NodePort
