apiVersion: v1
kind: Pod
metadata:
  labels:
    run: backend-location
  name: backend-location
spec:
  containers:
    - image: 192.168.178.17:5000/backend-location
      name: backend-location
      envFrom:
        - secretRef:
            name: opencage-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-service
  name: location-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    run: backend-location
  type: ClusterIP
